# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 8
    maxLineLength: 120
  NoWildcardImports:
    active: false
style:
  WildcardImport:
    active: false
complexity:
  LongMethod:
    active: true
    excludes: ['**/app_package/**']
